### ISSUE TITLE
Name is scrambled when updating company with special character in its name 

### ISSUE THREAD

**Issue by liorhar** [intercom/intercom-java#113]
## Version info
  - intercom-java version: 2.0.0
  - Java version: 1.8

## Expected behavior

We have companies with special characters in their names e.g. quotes or ampersands.
Updating such companies causes their name to include tons of &amp; then fail with message name too long
![image](https://cloud.githubusercontent.com/assets/821044/17356326/794208f0-595f-11e6-8ee6-683696db0f0d.png)
error: custom_attributes invalid, length too long: name 

## Steps to reproduce
```
      val company = Company.find(Map("company_id" -> companyStats.id.toString))
      if (company != null) {
        company.setName(companyStats.name)
        company.addCustomAttribute(CustomAttribute.newBooleanAttribute("hasDemoData", companyStats.hasDemoData))
        Company.update(company)
```

in case company name is Bony's Fashion for example

**Comment by bobjflong** [comment]
Hi @liorhar,

We escape identity attributes like `name` on output in the API, but it looks like we weren't unescaping HTML input on the `/companies` endpoint. We are doing this now so this issue shouldn't compound itself. Will you be able to fix up your data? Perhaps by searching for companies with HTML entities in their name?

**Comment by liorhar** [comment]
I'm not sure I understand your response. Are you saying that the read endpoint will now return the company name escaped, so when I update the company it should all just work?
My data is sanitized, I never send HTML elements in the name

**Comment by liorhar** [comment]
@bobjflong

**Comment by bobjflong** [comment]
We escape `name` in the API, so if your company name was `Foo & Bar`, it would be rendered as `Foo &amp; Bar` in the API response.

So if you read that name in the intercom-java client, and submitted an update, it would be stored as `Foo &amp; Bar`, and then re-rendered as `Foo &amp;amp; Bar`.

Now, after the bug fix if you submit `Foo &amp; Bar`, it will stay stored as `Foo & Bar`, and be rendered as `Foo &amp; Bar`. Does that make sense?

**Comment by liorhar** [comment]
Yes, it does.
So is the bug fixed already on your end?
Do I have to encode the name before updating the company using the java client or does it do it automatically?

**Comment by bobjflong** [comment]
The bug is fixed on our end. You can either submit `Foo & Bar` or `Foo &amp; Bar` and it will be stored as `Foo & Bar`in the datastore.

**Comment by liorhar** [comment]
I'm sorry but I'm still getting the following error when updating companies with special characters:
`updating Banes & Spot, message: custom_attributes invalid, length too long: name`

**Comment by bobjflong** [comment]
Is it possible that you have a really long custom attribute called `name`? Could you print out the Company object you are trying to save?

**Comment by liorhar** [comment]
It is possible, see the screenshot attached to the issue. But that's only because your endpoint has expanded a single ampersand into dozens of them. 
I set the new name which is short `Banes & Spot` yet it fails to update probably cause of the previous value.

**Comment by bobjflong** [comment]
But that's a custom_attribute? [`custom_attributes`](https://developers.intercom.io/reference#create-or-update-company) are key/value pairs that you can set arbitrarily. Are you using that alongside a normal `name` field?

**Comment by liorhar** [comment]
yes, I'm using custom attributes but those are either boolean or numeric so their value can't be long. This is the code snippet:
```
company.setName(companyStats.name)
        company.addCustomAttribute(CustomAttribute.newBooleanAttribute("hasDemoData", companyStats.hasDemoData))
        company.addCustomAttribute(CustomAttribute.newIntegerAttribute("filledFinancialInfo", companyStats.hasSignificantData))
        company.addCustomAttribute(CustomAttribute.newIntegerAttribute("employees", companyStats.numberOfEmployees))
        company.addCustomAttribute(CustomAttribute.newIntegerAttribute("size", companyStats.size))
        company.addCustomAttribute(CustomAttribute.newDoubleAttribute("averageAge", companyStats.averageAge))
        company.setRemoteCreatedAt(companyStats.createdAt.atZone(ZoneOffset.UTC).toEpochSecond)
        if (companyStats.numberOfDaysLeftToTrial.isDefined) company.addCustomAttribute(CustomAttribute.newIntegerAttribute("numberOfDaysLeftToTrial", companyStats.numberOfDaysLeftToTrial.get))
        Company.update(company)
        ```

**Comment by bobjflong** [comment]
OK - could you give me some information to track down the failing request. Do you have an app_id, or better yet a request_id from the failed call?

**Comment by liorhar** [comment]
can we move this discussion to a private channel?

**Comment by bobjflong** [comment]
Yep, feel free to get in touch through the Intercom widget (ask for bob)
